In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('customer.csv')

In [4]:
df.shape

(50, 5)

In [9]:
df.sample(5)

age  gender   review education purchased
30   73    Male  Average        UG        No
32   92    Male  Average        UG       Yes
24   16  Female  Average        PG       Yes
48   39  Female     Good        UG       Yes
22   18  Female     Poor        PG       Yes

In [19]:
df = df.iloc[:,2:]

In [22]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1], test_size=0.2)

In [28]:
from sklearn.preprocessing import OrdinalEncoder

In [21]:
X_train

review education
35     Poor    School
32  Average        UG
47     Good        PG
3      Good        PG
39     Poor        PG
2      Good        PG
12     Poor    School
44  Average        UG
45     Poor        PG
42     Good        PG
13  Average    School
7      Poor    School
26     Poor        PG
28     Poor    School
14     Poor        PG
43     Poor        PG
20  Average    School
30  Average        UG
15     Poor        UG
6      Good    School
10     Good        UG
33     Good        PG
9      Good        UG
23     Good    School
0   Average    School
4   Average        UG
36     Good        UG
37  Average        PG
27     Poor        PG
5   Average    School
25     Good    School
1      Poor        UG
18     Good    School
31     Poor    School
21  Average        PG
24  Average        PG
16     Poor        UG
38     Good    School
29  Average        UG
48     Good        UG

In [35]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [36]:
oe.fit(X_train)

ValueError: could not convert string to float: 'Poor'

In [37]:
X_train = oe.transform(X_train)

ValueError: The number of features in X is different to the number of features of the fitted data. The fitted data had 0 features and the X has 2 features.

In [38]:
X_train

array([[0., 0.],
       [1., 1.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [0., 0.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [0., 0.],
       [0., 2.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [1., 0.],
       [1., 1.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [2., 2.],
       [2., 1.],
       [2., 0.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [1., 0.],
       [2., 0.],
       [0., 1.],
       [2., 0.],
       [0., 0.],
       [1., 2.],
       [1., 2.],
       [0., 1.],
       [2., 0.],
       [1., 1.],
       [2., 1.]])

In [39]:
oe.categories_

[]

In [40]:
X_train

array([[0., 0.],
       [1., 1.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [0., 0.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [0., 0.],
       [0., 2.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [1., 0.],
       [1., 1.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [2., 2.],
       [2., 1.],
       [2., 0.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [1., 0.],
       [2., 0.],
       [0., 1.],
       [2., 0.],
       [0., 0.],
       [1., 2.],
       [1., 2.],
       [0., 1.],
       [2., 0.],
       [1., 1.],
       [2., 1.]])

In [41]:
from sklearn.preprocessing import LabelEncoder

In [42]:
le = LabelEncoder()

In [43]:
le.fit(y_train)

LabelEncoder()

In [44]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [45]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [46]:
y_train

array([1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1])